# Generated by Django 4.2.4 on 2024-05-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='lecture',
            new_name='lecturer',
        ),
    ]
