# Generated by Django 4.2.4 on 2024-05-08 07:06

from django.db import migrations

def set_rarity(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')

    items = item_model.objects.all()

    for item_object in items:
        if item_object.price <= 10:
            item_object.rarity = 'Rare'
        elif 10 <= item_object.price <= 20:
            item_object.rarity = 'Very Rare'
        elif 21 <= item_object.price <= 30:
            item_object.rarity = 'Extremely Rare'
        else:
            item_object.rarity = 'Mega Rare'

    item_model.objects.bulk_update (items, ['rarity'])

def set_default_rarity(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')

    items = item_model.objects.all()

    rarity_default = item_model._meta.get_field('rarity').default

    for item_object in items:
        item_object.rarity = rarity_default

    item_model.objects.bulk_update(items, ['rarity'])

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_item'),
    ]

    operations = [
    ]
