# Generated by Django 4.2.4 on 2024-05-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_product_created_on_product_last_edited_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(),
        ),
    ]
