# Generated by Django 5.0.4 on 2024-06-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bird',
            old_name='wings_span',
            new_name='wing_span',
        ),
    ]
