# Generated by Django 5.0.4 on 2024-06-04 08:07

import main_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='availability',
            field=main_app.models.BoolenaChoiceField(choices=[(True, 'Available'), (False, 'Not Available')], default=True),
        ),
    ]
