# Generated by Django 5.0.4 on 2024-06-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viperassassin',
            old_name='nomous_bite_ability',
            new_name='venomous_bite_ability',
        ),
    ]
